services:
  metadata_database:
    image: postgres:17
    container_name: metadata_database
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: metadata
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    command: >
      postgres -c max_connections=1000
               -c shared_buffers=256MB
               -c effective_cache_size=768MB
               -c maintenance_work_mem=64MB
               -c checkpoint_completion_target=0.7
               -c wal_buffers=16MB
               -c default_statistics_target=100
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d metadata" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    tty: true
    stdin_open: true

  metadata_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: metadata_service
    restart: always
    ports:
      - "8005:8005"
    depends_on:
      - metadata_database
    environment:
      DB_USER: user
      DB_PASSWORD: 12345678
      DB_HOST: metadata_database
      DB_PORT: 5435
      DB_NAME: metadata
    volumes:
      - .:/src


volumes:
  pgdata:
    driver: local