# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: listener.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'listener.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0elistener.proto\x12\x08listener\")\n\x12GetListenerRequest\x12\x13\n\x0blistener_id\x18\x01 \x01(\x05\"b\n\x13GetListenerResponse\x12\x13\n\x0blistener_id\x18\x01 \x01(\x05\x12\x0f\n\x07user_id\x18\x02 \x01(\x05\x12\x12\n\nfirst_name\x18\x03 \x01(\t\x12\x11\n\tlast_name\x18\x04 \x01(\t2]\n\x0fListenerService\x12J\n\x0bGetListener\x12\x1c.listener.GetListenerRequest\x1a\x1d.listener.GetListenerResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'listener_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETLISTENERREQUEST']._serialized_start=28
  _globals['_GETLISTENERREQUEST']._serialized_end=69
  _globals['_GETLISTENERRESPONSE']._serialized_start=71
  _globals['_GETLISTENERRESPONSE']._serialized_end=169
  _globals['_LISTENERSERVICE']._serialized_start=171
  _globals['_LISTENERSERVICE']._serialized_end=264
# @@protoc_insertion_point(module_scope)