# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import grpcc.listener_pb2 as listener__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in listener_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ListenerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetListener = channel.unary_unary(
                '/listener.ListenerService/GetListener',
                request_serializer=listener__pb2.GetListenerRequest.SerializeToString,
                response_deserializer=listener__pb2.GetListenerResponse.FromString,
                _registered_method=True)
        self.CreateListener = channel.unary_unary(
                '/listener.ListenerService/CreateListener',
                request_serializer=listener__pb2.CreateListenerRequest.SerializeToString,
                response_deserializer=listener__pb2.CreateListenerResponse.FromString,
                _registered_method=True)
        self.DeleteListener = channel.unary_unary(
                '/listener.ListenerService/DeleteListener',
                request_serializer=listener__pb2.DeleteListenerRequest.SerializeToString,
                response_deserializer=listener__pb2.DeleteListenerResponse.FromString,
                _registered_method=True)
        self.Like = channel.unary_unary(
                '/listener.ListenerService/Like',
                request_serializer=listener__pb2.LikeRequest.SerializeToString,
                response_deserializer=listener__pb2.LikeResponse.FromString,
                _registered_method=True)
        self.Interaction = channel.unary_unary(
                '/listener.ListenerService/Interaction',
                request_serializer=listener__pb2.InteractionRequest.SerializeToString,
                response_deserializer=listener__pb2.InteractionResponse.FromString,
                _registered_method=True)
        self.History = channel.unary_unary(
                '/listener.ListenerService/History',
                request_serializer=listener__pb2.HistoryRequest.SerializeToString,
                response_deserializer=listener__pb2.HistoryResponse.FromString,
                _registered_method=True)
        self.CreatePlaylist = channel.unary_unary(
                '/listener.ListenerService/CreatePlaylist',
                request_serializer=listener__pb2.CreatePlaylistRequest.SerializeToString,
                response_deserializer=listener__pb2.PlaylistResponse.FromString,
                _registered_method=True)
        self.DeletePlaylist = channel.unary_unary(
                '/listener.ListenerService/DeletePlaylist',
                request_serializer=listener__pb2.DeletePlaylistRequest.SerializeToString,
                response_deserializer=listener__pb2.DeletePlaylistResponse.FromString,
                _registered_method=True)
        self.GetAllPlaylists = channel.unary_unary(
                '/listener.ListenerService/GetAllPlaylists',
                request_serializer=listener__pb2.GetAllPlaylistsRequest.SerializeToString,
                response_deserializer=listener__pb2.GetAllPlaylistsResponse.FromString,
                _registered_method=True)
        self.AddNewTrackInPlaylist = channel.unary_unary(
                '/listener.ListenerService/AddNewTrackInPlaylist',
                request_serializer=listener__pb2.AddNewTrackInPlaylistRequest.SerializeToString,
                response_deserializer=listener__pb2.TrackInPlaylistResponse.FromString,
                _registered_method=True)
        self.DeleteTrackFromPlaylist = channel.unary_unary(
                '/listener.ListenerService/DeleteTrackFromPlaylist',
                request_serializer=listener__pb2.DeleteTrackFromPlaylistRequest.SerializeToString,
                response_deserializer=listener__pb2.DeleteTrackFromPlaylistResponse.FromString,
                _registered_method=True)
        self.GetAllTracksInPlaylist = channel.unary_unary(
                '/listener.ListenerService/GetAllTracksInPlaylist',
                request_serializer=listener__pb2.GetAllTracksInPlaylistRequest.SerializeToString,
                response_deserializer=listener__pb2.GetAllTracksInPlaylistResponse.FromString,
                _registered_method=True)


class ListenerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetListener(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateListener(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteListener(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Like(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Interaction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def History(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreatePlaylist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePlaylist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllPlaylists(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddNewTrackInPlaylist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteTrackFromPlaylist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllTracksInPlaylist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ListenerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetListener': grpc.unary_unary_rpc_method_handler(
                    servicer.GetListener,
                    request_deserializer=listener__pb2.GetListenerRequest.FromString,
                    response_serializer=listener__pb2.GetListenerResponse.SerializeToString,
            ),
            'CreateListener': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateListener,
                    request_deserializer=listener__pb2.CreateListenerRequest.FromString,
                    response_serializer=listener__pb2.CreateListenerResponse.SerializeToString,
            ),
            'DeleteListener': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteListener,
                    request_deserializer=listener__pb2.DeleteListenerRequest.FromString,
                    response_serializer=listener__pb2.DeleteListenerResponse.SerializeToString,
            ),
            'Like': grpc.unary_unary_rpc_method_handler(
                    servicer.Like,
                    request_deserializer=listener__pb2.LikeRequest.FromString,
                    response_serializer=listener__pb2.LikeResponse.SerializeToString,
            ),
            'Interaction': grpc.unary_unary_rpc_method_handler(
                    servicer.Interaction,
                    request_deserializer=listener__pb2.InteractionRequest.FromString,
                    response_serializer=listener__pb2.InteractionResponse.SerializeToString,
            ),
            'History': grpc.unary_unary_rpc_method_handler(
                    servicer.History,
                    request_deserializer=listener__pb2.HistoryRequest.FromString,
                    response_serializer=listener__pb2.HistoryResponse.SerializeToString,
            ),
            'CreatePlaylist': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePlaylist,
                    request_deserializer=listener__pb2.CreatePlaylistRequest.FromString,
                    response_serializer=listener__pb2.PlaylistResponse.SerializeToString,
            ),
            'DeletePlaylist': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePlaylist,
                    request_deserializer=listener__pb2.DeletePlaylistRequest.FromString,
                    response_serializer=listener__pb2.DeletePlaylistResponse.SerializeToString,
            ),
            'GetAllPlaylists': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllPlaylists,
                    request_deserializer=listener__pb2.GetAllPlaylistsRequest.FromString,
                    response_serializer=listener__pb2.GetAllPlaylistsResponse.SerializeToString,
            ),
            'AddNewTrackInPlaylist': grpc.unary_unary_rpc_method_handler(
                    servicer.AddNewTrackInPlaylist,
                    request_deserializer=listener__pb2.AddNewTrackInPlaylistRequest.FromString,
                    response_serializer=listener__pb2.TrackInPlaylistResponse.SerializeToString,
            ),
            'DeleteTrackFromPlaylist': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteTrackFromPlaylist,
                    request_deserializer=listener__pb2.DeleteTrackFromPlaylistRequest.FromString,
                    response_serializer=listener__pb2.DeleteTrackFromPlaylistResponse.SerializeToString,
            ),
            'GetAllTracksInPlaylist': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllTracksInPlaylist,
                    request_deserializer=listener__pb2.GetAllTracksInPlaylistRequest.FromString,
                    response_serializer=listener__pb2.GetAllTracksInPlaylistResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'listener.ListenerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('listener.ListenerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ListenerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetListener(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/listener.ListenerService/GetListener',
            listener__pb2.GetListenerRequest.SerializeToString,
            listener__pb2.GetListenerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateListener(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/listener.ListenerService/CreateListener',
            listener__pb2.CreateListenerRequest.SerializeToString,
            listener__pb2.CreateListenerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteListener(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/listener.ListenerService/DeleteListener',
            listener__pb2.DeleteListenerRequest.SerializeToString,
            listener__pb2.DeleteListenerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Like(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/listener.ListenerService/Like',
            listener__pb2.LikeRequest.SerializeToString,
            listener__pb2.LikeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Interaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/listener.ListenerService/Interaction',
            listener__pb2.InteractionRequest.SerializeToString,
            listener__pb2.InteractionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def History(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/listener.ListenerService/History',
            listener__pb2.HistoryRequest.SerializeToString,
            listener__pb2.HistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreatePlaylist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/listener.ListenerService/CreatePlaylist',
            listener__pb2.CreatePlaylistRequest.SerializeToString,
            listener__pb2.PlaylistResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeletePlaylist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/listener.ListenerService/DeletePlaylist',
            listener__pb2.DeletePlaylistRequest.SerializeToString,
            listener__pb2.DeletePlaylistResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllPlaylists(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/listener.ListenerService/GetAllPlaylists',
            listener__pb2.GetAllPlaylistsRequest.SerializeToString,
            listener__pb2.GetAllPlaylistsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddNewTrackInPlaylist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/listener.ListenerService/AddNewTrackInPlaylist',
            listener__pb2.AddNewTrackInPlaylistRequest.SerializeToString,
            listener__pb2.TrackInPlaylistResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteTrackFromPlaylist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/listener.ListenerService/DeleteTrackFromPlaylist',
            listener__pb2.DeleteTrackFromPlaylistRequest.SerializeToString,
            listener__pb2.DeleteTrackFromPlaylistResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllTracksInPlaylist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/listener.ListenerService/GetAllTracksInPlaylist',
            listener__pb2.GetAllTracksInPlaylistRequest.SerializeToString,
            listener__pb2.GetAllTracksInPlaylistResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
