"""New relations to user id

Revision ID: ce9104a763c1
Revises: b457991d4726
Create Date: 2025-05-20 16:10:00.185396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce9104a763c1'
down_revision: Union[str, None] = 'b457991d4726'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'User', ['user_id'])
    op.drop_constraint('Interactions_user_id_fkey', 'Interactions', type_='foreignkey')
    op.create_foreign_key(None, 'Interactions', 'User', ['user_id'], ['user_id'])
    op.drop_constraint('TrackLikes_user_id_fkey', 'TrackLikes', type_='foreignkey')
    op.create_foreign_key(None, 'TrackLikes', 'User', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'User', type_='unique')
    op.drop_constraint(None, 'TrackLikes', type_='foreignkey')
    op.create_foreign_key('TrackLikes_user_id_fkey', 'TrackLikes', 'User', ['user_id'], ['id'])
    op.drop_constraint(None, 'Interactions', type_='foreignkey')
    op.create_foreign_key('Interactions_user_id_fkey', 'Interactions', 'User', ['user_id'], ['id'])
    # ### end Alembic commands ###
