# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import src.grpc.artist_pb2 as artist__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in artist_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ArtistServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetDescription = channel.unary_unary(
                '/artist.ArtistService/GetDescription',
                request_serializer=artist__pb2.GetDescriptionRequest.SerializeToString,
                response_deserializer=artist__pb2.GetDescriptionResponse.FromString,
                _registered_method=True)
        self.CreateArtist = channel.unary_unary(
                '/artist.ArtistService/CreateArtist',
                request_serializer=artist__pb2.CreateArtistRequest.SerializeToString,
                response_deserializer=artist__pb2.CreateArtistResponse.FromString,
                _registered_method=True)
        self.UploadFileMP3 = channel.stream_unary(
                '/artist.ArtistService/UploadFileMP3',
                request_serializer=artist__pb2.FileChunk.SerializeToString,
                response_deserializer=artist__pb2.UploadStatus.FromString,
                _registered_method=True)
        self.UploadArtistCover = channel.stream_unary(
                '/artist.ArtistService/UploadArtistCover',
                request_serializer=artist__pb2.FileChunk.SerializeToString,
                response_deserializer=artist__pb2.UploadStatus.FromString,
                _registered_method=True)


class ArtistServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetDescription(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateArtist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadFileMP3(self, request_iterator, context):
        """методы для работы с файлами
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadArtistCover(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ArtistServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetDescription': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDescription,
                    request_deserializer=artist__pb2.GetDescriptionRequest.FromString,
                    response_serializer=artist__pb2.GetDescriptionResponse.SerializeToString,
            ),
            'CreateArtist': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateArtist,
                    request_deserializer=artist__pb2.CreateArtistRequest.FromString,
                    response_serializer=artist__pb2.CreateArtistResponse.SerializeToString,
            ),
            'UploadFileMP3': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadFileMP3,
                    request_deserializer=artist__pb2.FileChunk.FromString,
                    response_serializer=artist__pb2.UploadStatus.SerializeToString,
            ),
            'UploadArtistCover': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadArtistCover,
                    request_deserializer=artist__pb2.FileChunk.FromString,
                    response_serializer=artist__pb2.UploadStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'artist.ArtistService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('artist.ArtistService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ArtistService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetDescription(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/artist.ArtistService/GetDescription',
            artist__pb2.GetDescriptionRequest.SerializeToString,
            artist__pb2.GetDescriptionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateArtist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/artist.ArtistService/CreateArtist',
            artist__pb2.CreateArtistRequest.SerializeToString,
            artist__pb2.CreateArtistResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadFileMP3(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/artist.ArtistService/UploadFileMP3',
            artist__pb2.FileChunk.SerializeToString,
            artist__pb2.UploadStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadArtistCover(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/artist.ArtistService/UploadArtistCover',
            artist__pb2.FileChunk.SerializeToString,
            artist__pb2.UploadStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
