# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import src.grpc.artist_pb2 as artist__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in artist_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ArtistServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetArtistDataByUserId = channel.unary_unary(
                '/artist.ArtistService/GetArtistDataByUserId',
                request_serializer=artist__pb2.GetArtistDataByUserIdRequest.SerializeToString,
                response_deserializer=artist__pb2.GetArtistDataByUserIdResponse.FromString,
                _registered_method=True)
        self.CreateArtist = channel.unary_unary(
                '/artist.ArtistService/CreateArtist',
                request_serializer=artist__pb2.CreateArtistRequest.SerializeToString,
                response_deserializer=artist__pb2.CreateArtistResponse.FromString,
                _registered_method=True)
        self.GetArtistDataById = channel.unary_unary(
                '/artist.ArtistService/GetArtistDataById',
                request_serializer=artist__pb2.GetArtistDataByIdRequest.SerializeToString,
                response_deserializer=artist__pb2.GetArtistDataByIdResponse.FromString,
                _registered_method=True)
        self.GetArtistId = channel.unary_unary(
                '/artist.ArtistService/GetArtistId',
                request_serializer=artist__pb2.GetArtistIdRequest.SerializeToString,
                response_deserializer=artist__pb2.GetArtistIdResponse.FromString,
                _registered_method=True)
        self.DeleteArtistByUserId = channel.unary_unary(
                '/artist.ArtistService/DeleteArtistByUserId',
                request_serializer=artist__pb2.DeleteArtistByUserIdRequest.SerializeToString,
                response_deserializer=artist__pb2.DeleteArtistByUserIdResponse.FromString,
                _registered_method=True)


class ArtistServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetArtistDataByUserId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateArtist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetArtistDataById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetArtistId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteArtistByUserId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ArtistServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetArtistDataByUserId': grpc.unary_unary_rpc_method_handler(
                    servicer.GetArtistDataByUserId,
                    request_deserializer=artist__pb2.GetArtistDataByUserIdRequest.FromString,
                    response_serializer=artist__pb2.GetArtistDataByUserIdResponse.SerializeToString,
            ),
            'CreateArtist': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateArtist,
                    request_deserializer=artist__pb2.CreateArtistRequest.FromString,
                    response_serializer=artist__pb2.CreateArtistResponse.SerializeToString,
            ),
            'GetArtistDataById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetArtistDataById,
                    request_deserializer=artist__pb2.GetArtistDataByIdRequest.FromString,
                    response_serializer=artist__pb2.GetArtistDataByIdResponse.SerializeToString,
            ),
            'GetArtistId': grpc.unary_unary_rpc_method_handler(
                    servicer.GetArtistId,
                    request_deserializer=artist__pb2.GetArtistIdRequest.FromString,
                    response_serializer=artist__pb2.GetArtistIdResponse.SerializeToString,
            ),
            'DeleteArtistByUserId': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteArtistByUserId,
                    request_deserializer=artist__pb2.DeleteArtistByUserIdRequest.FromString,
                    response_serializer=artist__pb2.DeleteArtistByUserIdResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'artist.ArtistService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('artist.ArtistService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ArtistService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetArtistDataByUserId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/artist.ArtistService/GetArtistDataByUserId',
            artist__pb2.GetArtistDataByUserIdRequest.SerializeToString,
            artist__pb2.GetArtistDataByUserIdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateArtist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/artist.ArtistService/CreateArtist',
            artist__pb2.CreateArtistRequest.SerializeToString,
            artist__pb2.CreateArtistResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetArtistDataById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/artist.ArtistService/GetArtistDataById',
            artist__pb2.GetArtistDataByIdRequest.SerializeToString,
            artist__pb2.GetArtistDataByIdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetArtistId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/artist.ArtistService/GetArtistId',
            artist__pb2.GetArtistIdRequest.SerializeToString,
            artist__pb2.GetArtistIdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteArtistByUserId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/artist.ArtistService/DeleteArtistByUserId',
            artist__pb2.DeleteArtistByUserIdRequest.SerializeToString,
            artist__pb2.DeleteArtistByUserIdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
