services:
  reader_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reader_service
    restart: always
    ports:
      - "8802:8802"
    networks:
      - music_network
    environment:
      DB_USER: user
      DB_PASSWORD: 12345678
      DB_HOST: metadata_database
      DB_PORT: 5435
      DB_NAME: metadata
    volumes:
      - .:/src

volumes:
  pgdata:
    driver: local

networks:
  music_network:
    name: music_network
