"""set user id unique and make not nulable name and user_id

Revision ID: a18fbbda67f2
Revises: 193834eef266
Create Date: 2025-05-19 23:59:20.147554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a18fbbda67f2'
down_revision: Union[str, None] = '193834eef266'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artists', 'name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('artists', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint(None, 'artists', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'artists', type_='unique')
    op.alter_column('artists', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('artists', 'name',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
