# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: reader.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'reader.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0creader.proto\x12\x06reader\"#\n\x0fGetTrackRequest\x12\x10\n\x08track_id\x18\x01 \x01(\x05\"W\n\x10GetTrackResponse\x12\x10\n\x08track_id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x10\n\x08\x61lbum_id\x18\x03 \x01(\x05\x12\x10\n\x08\x65xplicit\x18\x04 \x01(\x08\"+\n\x17GetTracksInAlbumRequest\x12\x10\n\x08\x61lbum_id\x18\x01 \x01(\x05\"D\n\x18GetTracksInAlbumResponse\x12(\n\x06tracks\x18\x01 \x03(\x0b\x32\x18.reader.GetTrackResponse\"#\n\x0fGetAlbumRequest\x12\x10\n\x08\x61lbum_id\x18\x01 \x01(\x05\"\\\n\x10GetAlbumResponse\x12\x10\n\x08\x61lbum_id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x11\n\tartist_id\x18\x03 \x01(\x05\x12\x14\n\x0crelease_date\x18\x04 \x01(\t\",\n\x17GetAlbumInArtistRequest\x12\x11\n\tartist_id\x18\x01 \x01(\x05\"D\n\x18GetAlbumInArtistResponse\x12(\n\x06\x61lbums\x18\x01 \x03(\x0b\x32\x18.reader.GetAlbumResponse\"(\n\x14GetTrackGenreRequest\x12\x10\n\x08track_id\x18\x01 \x01(\x05\"=\n\x15GetTrackGenreResponse\x12\x10\n\x08genre_id\x18\x01 \x01(\x05\x12\x12\n\ngenre_name\x18\x02 \x01(\t\"\x15\n\x13GetAllAlbumsRequest\"@\n\x14GetAllAlbumsResponse\x12(\n\x06\x61lbums\x18\x01 \x03(\x0b\x32\x18.reader.GetAlbumResponse2\xd4\x03\n\rReaderService\x12=\n\x08GetTrack\x12\x17.reader.GetTrackRequest\x1a\x18.reader.GetTrackResponse\x12U\n\x10GetTracksInAlbum\x12\x1f.reader.GetTracksInAlbumRequest\x1a .reader.GetTracksInAlbumResponse\x12=\n\x08GetAlbum\x12\x17.reader.GetAlbumRequest\x1a\x18.reader.GetAlbumResponse\x12U\n\x10GetAlbumInArtist\x12\x1f.reader.GetAlbumInArtistRequest\x1a .reader.GetAlbumInArtistResponse\x12L\n\rGetTrackGenre\x12\x1c.reader.GetTrackGenreRequest\x1a\x1d.reader.GetTrackGenreResponse\x12I\n\x0cGetAllAlbums\x12\x1b.reader.GetAllAlbumsRequest\x1a\x1c.reader.GetAllAlbumsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'reader_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETTRACKREQUEST']._serialized_start=24
  _globals['_GETTRACKREQUEST']._serialized_end=59
  _globals['_GETTRACKRESPONSE']._serialized_start=61
  _globals['_GETTRACKRESPONSE']._serialized_end=148
  _globals['_GETTRACKSINALBUMREQUEST']._serialized_start=150
  _globals['_GETTRACKSINALBUMREQUEST']._serialized_end=193
  _globals['_GETTRACKSINALBUMRESPONSE']._serialized_start=195
  _globals['_GETTRACKSINALBUMRESPONSE']._serialized_end=263
  _globals['_GETALBUMREQUEST']._serialized_start=265
  _globals['_GETALBUMREQUEST']._serialized_end=300
  _globals['_GETALBUMRESPONSE']._serialized_start=302
  _globals['_GETALBUMRESPONSE']._serialized_end=394
  _globals['_GETALBUMINARTISTREQUEST']._serialized_start=396
  _globals['_GETALBUMINARTISTREQUEST']._serialized_end=440
  _globals['_GETALBUMINARTISTRESPONSE']._serialized_start=442
  _globals['_GETALBUMINARTISTRESPONSE']._serialized_end=510
  _globals['_GETTRACKGENREREQUEST']._serialized_start=512
  _globals['_GETTRACKGENREREQUEST']._serialized_end=552
  _globals['_GETTRACKGENRERESPONSE']._serialized_start=554
  _globals['_GETTRACKGENRERESPONSE']._serialized_end=615
  _globals['_GETALLALBUMSREQUEST']._serialized_start=617
  _globals['_GETALLALBUMSREQUEST']._serialized_end=638
  _globals['_GETALLALBUMSRESPONSE']._serialized_start=640
  _globals['_GETALLALBUMSRESPONSE']._serialized_end=704
  _globals['_READERSERVICE']._serialized_start=707
  _globals['_READERSERVICE']._serialized_end=1175
# @@protoc_insertion_point(module_scope)
