# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: artist.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'artist.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x61rtist.proto\x12\x06\x61rtist\"(\n\x15GetDescriptionRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"-\n\x16GetDescriptionResponse\x12\x13\n\x0b\x64\x65scription\x18\x01 \x01(\t\"X\n\x13\x43reateArtistRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x0f\n\x07user_id\x18\x04 \x01(\x05\"\"\n\x14\x43reateArtistResponse\x12\n\n\x02id\x18\x01 \x01(\x05\" \n\x0b\x46ileRequest\x12\x11\n\tfile_name\x18\x01 \x01(\t\"-\n\tFileChunk\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\x12\x0f\n\x07user_id\x18\x02 \x01(\x05\"0\n\x0cUploadStatus\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xa7\x02\n\rArtistService\x12O\n\x0eGetDescription\x12\x1d.artist.GetDescriptionRequest\x1a\x1e.artist.GetDescriptionResponse\x12I\n\x0c\x43reateArtist\x12\x1b.artist.CreateArtistRequest\x1a\x1c.artist.CreateArtistResponse\x12:\n\rUploadFileMP3\x12\x11.artist.FileChunk\x1a\x14.artist.UploadStatus(\x01\x12>\n\x11UploadArtistCover\x12\x11.artist.FileChunk\x1a\x14.artist.UploadStatus(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'artist_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETDESCRIPTIONREQUEST']._serialized_start=24
  _globals['_GETDESCRIPTIONREQUEST']._serialized_end=64
  _globals['_GETDESCRIPTIONRESPONSE']._serialized_start=66
  _globals['_GETDESCRIPTIONRESPONSE']._serialized_end=111
  _globals['_CREATEARTISTREQUEST']._serialized_start=113
  _globals['_CREATEARTISTREQUEST']._serialized_end=201
  _globals['_CREATEARTISTRESPONSE']._serialized_start=203
  _globals['_CREATEARTISTRESPONSE']._serialized_end=237
  _globals['_FILEREQUEST']._serialized_start=239
  _globals['_FILEREQUEST']._serialized_end=271
  _globals['_FILECHUNK']._serialized_start=273
  _globals['_FILECHUNK']._serialized_end=318
  _globals['_UPLOADSTATUS']._serialized_start=320
  _globals['_UPLOADSTATUS']._serialized_end=368
  _globals['_ARTISTSERVICE']._serialized_start=371
  _globals['_ARTISTSERVICE']._serialized_end=666
# @@protoc_insertion_point(module_scope)
