# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: artist.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'artist.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x61rtist.proto\x12\x06\x61rtist\x1a\x1fgoogle/protobuf/timestamp.proto\"/\n\x1cGetArtistDataByUserIdRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"-\n\x18GetArtistDataByIdRequest\x12\x11\n\tartist_id\x18\x01 \x01(\x05\"\x81\x01\n\x1dGetArtistDataByUserIdResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x31\n\rregistered_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"}\n\x19GetArtistDataByIdResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x31\n\rregistered_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"X\n\x13\x43reateArtistRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x0f\n\x07user_id\x18\x04 \x01(\x05\")\n\x14\x43reateArtistResponse\x12\x11\n\tartist_id\x18\x01 \x01(\x05\"%\n\x12GetArtistIdRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"!\n\x13GetArtistIdResponse\x12\n\n\x02id\x18\x01 \x01(\x05\".\n\x1b\x44\x65leteArtistByUserIdRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"/\n\x1c\x44\x65leteArtistByUserIdResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x32\xc5\x03\n\rArtistService\x12\x64\n\x15GetArtistDataByUserId\x12$.artist.GetArtistDataByUserIdRequest\x1a%.artist.GetArtistDataByUserIdResponse\x12I\n\x0c\x43reateArtist\x12\x1b.artist.CreateArtistRequest\x1a\x1c.artist.CreateArtistResponse\x12X\n\x11GetArtistDataById\x12 .artist.GetArtistDataByIdRequest\x1a!.artist.GetArtistDataByIdResponse\x12\x46\n\x0bGetArtistId\x12\x1a.artist.GetArtistIdRequest\x1a\x1b.artist.GetArtistIdResponse\x12\x61\n\x14\x44\x65leteArtistByUserId\x12#.artist.DeleteArtistByUserIdRequest\x1a$.artist.DeleteArtistByUserIdResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'artist_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETARTISTDATABYUSERIDREQUEST']._serialized_start=57
  _globals['_GETARTISTDATABYUSERIDREQUEST']._serialized_end=104
  _globals['_GETARTISTDATABYIDREQUEST']._serialized_start=106
  _globals['_GETARTISTDATABYIDREQUEST']._serialized_end=151
  _globals['_GETARTISTDATABYUSERIDRESPONSE']._serialized_start=154
  _globals['_GETARTISTDATABYUSERIDRESPONSE']._serialized_end=283
  _globals['_GETARTISTDATABYIDRESPONSE']._serialized_start=285
  _globals['_GETARTISTDATABYIDRESPONSE']._serialized_end=410
  _globals['_CREATEARTISTREQUEST']._serialized_start=412
  _globals['_CREATEARTISTREQUEST']._serialized_end=500
  _globals['_CREATEARTISTRESPONSE']._serialized_start=502
  _globals['_CREATEARTISTRESPONSE']._serialized_end=543
  _globals['_GETARTISTIDREQUEST']._serialized_start=545
  _globals['_GETARTISTIDREQUEST']._serialized_end=582
  _globals['_GETARTISTIDRESPONSE']._serialized_start=584
  _globals['_GETARTISTIDRESPONSE']._serialized_end=617
  _globals['_DELETEARTISTBYUSERIDREQUEST']._serialized_start=619
  _globals['_DELETEARTISTBYUSERIDREQUEST']._serialized_end=665
  _globals['_DELETEARTISTBYUSERIDRESPONSE']._serialized_start=667
  _globals['_DELETEARTISTBYUSERIDRESPONSE']._serialized_end=714
  _globals['_ARTISTSERVICE']._serialized_start=717
  _globals['_ARTISTSERVICE']._serialized_end=1170
# @@protoc_insertion_point(module_scope)
