# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x04\x61uth\"3\n\x10UserLoginRequest\x12\r\n\x05login\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"@\n\x11UserLoginResponse\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\x12\x15\n\rrefresh_token\x18\x02 \x01(\t\";\n\x0cGetMeRequest\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\x12\x15\n\rrefresh_token\x18\x02 \x01(\t\"S\n\rGetMeResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\r\n\x05login\x18\x02 \x01(\t\x12\x0c\n\x04role\x18\x03 \x01(\t\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x04 \x01(\t\"D\n\x13UserRegisterRequest\x12\r\n\x05login\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x0c\n\x04role\x18\x03 \x01(\t\"\'\n\x14UserRegisterResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\"\n\x11UserDeleteRequest\x12\r\n\x05login\x18\x01 \x01(\t\"%\n\x12UserDeleteResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\x85\x02\n\x0b\x41uthService\x12<\n\tUserLogin\x12\x16.auth.UserLoginRequest\x1a\x17.auth.UserLoginResponse\x12\x30\n\x05GetMe\x12\x12.auth.GetMeRequest\x1a\x13.auth.GetMeResponse\x12\x45\n\x0cUserRegister\x12\x19.auth.UserRegisterRequest\x1a\x1a.auth.UserRegisterResponse\x12?\n\nUserDelete\x12\x17.auth.UserDeleteRequest\x1a\x18.auth.UserDeleteResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERLOGINREQUEST']._serialized_start=20
  _globals['_USERLOGINREQUEST']._serialized_end=71
  _globals['_USERLOGINRESPONSE']._serialized_start=73
  _globals['_USERLOGINRESPONSE']._serialized_end=137
  _globals['_GETMEREQUEST']._serialized_start=139
  _globals['_GETMEREQUEST']._serialized_end=198
  _globals['_GETMERESPONSE']._serialized_start=200
  _globals['_GETMERESPONSE']._serialized_end=283
  _globals['_USERREGISTERREQUEST']._serialized_start=285
  _globals['_USERREGISTERREQUEST']._serialized_end=353
  _globals['_USERREGISTERRESPONSE']._serialized_start=355
  _globals['_USERREGISTERRESPONSE']._serialized_end=394
  _globals['_USERDELETEREQUEST']._serialized_start=396
  _globals['_USERDELETEREQUEST']._serialized_end=430
  _globals['_USERDELETERESPONSE']._serialized_start=432
  _globals['_USERDELETERESPONSE']._serialized_end=469
  _globals['_AUTHSERVICE']._serialized_start=472
  _globals['_AUTHSERVICE']._serialized_end=733
# @@protoc_insertion_point(module_scope)
