# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import app.grpc_clients.reader_pb2 as reader__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in reader_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ReaderServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTrack = channel.unary_unary(
                '/reader.ReaderService/GetTrack',
                request_serializer=reader__pb2.GetTrackRequest.SerializeToString,
                response_deserializer=reader__pb2.GetTrackResponse.FromString,
                _registered_method=True)
        self.GetTracksInAlbum = channel.unary_unary(
                '/reader.ReaderService/GetTracksInAlbum',
                request_serializer=reader__pb2.GetTracksInAlbumRequest.SerializeToString,
                response_deserializer=reader__pb2.GetTracksInAlbumResponse.FromString,
                _registered_method=True)
        self.GetAlbum = channel.unary_unary(
                '/reader.ReaderService/GetAlbum',
                request_serializer=reader__pb2.GetAlbumRequest.SerializeToString,
                response_deserializer=reader__pb2.GetAlbumResponse.FromString,
                _registered_method=True)
        self.GetAlbumInArtist = channel.unary_unary(
                '/reader.ReaderService/GetAlbumInArtist',
                request_serializer=reader__pb2.GetAlbumInArtistRequest.SerializeToString,
                response_deserializer=reader__pb2.GetAlbumInArtistResponse.FromString,
                _registered_method=True)
        self.GetTrackGenre = channel.unary_unary(
                '/reader.ReaderService/GetTrackGenre',
                request_serializer=reader__pb2.GetTrackGenreRequest.SerializeToString,
                response_deserializer=reader__pb2.GetTrackGenreResponse.FromString,
                _registered_method=True)


class ReaderServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetTrack(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTracksInAlbum(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAlbum(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAlbumInArtist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTrackGenre(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReaderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTrack': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTrack,
                    request_deserializer=reader__pb2.GetTrackRequest.FromString,
                    response_serializer=reader__pb2.GetTrackResponse.SerializeToString,
            ),
            'GetTracksInAlbum': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTracksInAlbum,
                    request_deserializer=reader__pb2.GetTracksInAlbumRequest.FromString,
                    response_serializer=reader__pb2.GetTracksInAlbumResponse.SerializeToString,
            ),
            'GetAlbum': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAlbum,
                    request_deserializer=reader__pb2.GetAlbumRequest.FromString,
                    response_serializer=reader__pb2.GetAlbumResponse.SerializeToString,
            ),
            'GetAlbumInArtist': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAlbumInArtist,
                    request_deserializer=reader__pb2.GetAlbumInArtistRequest.FromString,
                    response_serializer=reader__pb2.GetAlbumInArtistResponse.SerializeToString,
            ),
            'GetTrackGenre': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTrackGenre,
                    request_deserializer=reader__pb2.GetTrackGenreRequest.FromString,
                    response_serializer=reader__pb2.GetTrackGenreResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'reader.ReaderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('reader.ReaderService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ReaderService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetTrack(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/reader.ReaderService/GetTrack',
            reader__pb2.GetTrackRequest.SerializeToString,
            reader__pb2.GetTrackResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTracksInAlbum(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/reader.ReaderService/GetTracksInAlbum',
            reader__pb2.GetTracksInAlbumRequest.SerializeToString,
            reader__pb2.GetTracksInAlbumResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAlbum(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/reader.ReaderService/GetAlbum',
            reader__pb2.GetAlbumRequest.SerializeToString,
            reader__pb2.GetAlbumResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAlbumInArtist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/reader.ReaderService/GetAlbumInArtist',
            reader__pb2.GetAlbumInArtistRequest.SerializeToString,
            reader__pb2.GetAlbumInArtistResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTrackGenre(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/reader.ReaderService/GetTrackGenre',
            reader__pb2.GetTrackGenreRequest.SerializeToString,
            reader__pb2.GetTrackGenreResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
