# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: writer.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'writer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cwriter.proto\x12\x06writer\x1a\x1fgoogle/protobuf/timestamp.proto\"h\n\x13\x43reateAlbum_Request\x12\r\n\x05title\x18\x01 \x01(\t\x12\x10\n\x08owner_id\x18\x02 \x01(\x05\x12\x30\n\x0crelease_date\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"(\n\x14\x43reateAlbum_Response\x12\x10\n\x08\x61lbum_id\x18\x01 \x01(\x05\"\'\n\x13RemoveAlbum_Request\x12\x10\n\x08\x61lbum_id\x18\x01 \x01(\x05\"(\n\x14RemoveAlbum_Response\x12\x10\n\x08\x61lbum_id\x18\x01 \x01(\x05\"1\n\x1dRemoveAlbumsByOwnerID_Request\x12\x10\n\x08owner_id\x18\x01 \x01(\x05\"3\n\x1eRemoveAlbumsByOwnerID_Response\x12\x11\n\talbum_ids\x18\x01 \x03(\x05\"]\n\x13\x43reateTrack_Request\x12\r\n\x05title\x18\x01 \x01(\t\x12\x10\n\x08\x61lbum_id\x18\x02 \x01(\x05\x12\x10\n\x08\x65xplicit\x18\x03 \x01(\x08\x12\x13\n\x0bgenre_names\x18\x04 \x03(\t\"(\n\x14\x43reateTrack_Response\x12\x10\n\x08track_id\x18\x01 \x01(\x05\"\'\n\x13RemoveTrack_Request\x12\x10\n\x08track_id\x18\x01 \x01(\x05\"(\n\x14RemoveTrack_Response\x12\x10\n\x08track_id\x18\x01 \x01(\x05\x32\x9f\x03\n\rWriterService\x12H\n\x0b\x43reateAlbum\x12\x1b.writer.CreateAlbum_Request\x1a\x1c.writer.CreateAlbum_Response\x12H\n\x0bRemoveAlbum\x12\x1b.writer.RemoveAlbum_Request\x1a\x1c.writer.RemoveAlbum_Response\x12\x66\n\x15RemoveAlbumsByOwnerID\x12%.writer.RemoveAlbumsByOwnerID_Request\x1a&.writer.RemoveAlbumsByOwnerID_Response\x12H\n\x0b\x43reateTrack\x12\x1b.writer.CreateTrack_Request\x1a\x1c.writer.CreateTrack_Response\x12H\n\x0bRemoveTrack\x12\x1b.writer.RemoveTrack_Request\x1a\x1c.writer.RemoveTrack_Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'writer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEALBUM_REQUEST']._serialized_start=57
  _globals['_CREATEALBUM_REQUEST']._serialized_end=161
  _globals['_CREATEALBUM_RESPONSE']._serialized_start=163
  _globals['_CREATEALBUM_RESPONSE']._serialized_end=203
  _globals['_REMOVEALBUM_REQUEST']._serialized_start=205
  _globals['_REMOVEALBUM_REQUEST']._serialized_end=244
  _globals['_REMOVEALBUM_RESPONSE']._serialized_start=246
  _globals['_REMOVEALBUM_RESPONSE']._serialized_end=286
  _globals['_REMOVEALBUMSBYOWNERID_REQUEST']._serialized_start=288
  _globals['_REMOVEALBUMSBYOWNERID_REQUEST']._serialized_end=337
  _globals['_REMOVEALBUMSBYOWNERID_RESPONSE']._serialized_start=339
  _globals['_REMOVEALBUMSBYOWNERID_RESPONSE']._serialized_end=390
  _globals['_CREATETRACK_REQUEST']._serialized_start=392
  _globals['_CREATETRACK_REQUEST']._serialized_end=485
  _globals['_CREATETRACK_RESPONSE']._serialized_start=487
  _globals['_CREATETRACK_RESPONSE']._serialized_end=527
  _globals['_REMOVETRACK_REQUEST']._serialized_start=529
  _globals['_REMOVETRACK_REQUEST']._serialized_end=568
  _globals['_REMOVETRACK_RESPONSE']._serialized_start=570
  _globals['_REMOVETRACK_RESPONSE']._serialized_end=610
  _globals['_WRITERSERVICE']._serialized_start=613
  _globals['_WRITERSERVICE']._serialized_end=1028
# @@protoc_insertion_point(module_scope)
