# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import app.grpc_clients.writer_pb2 as writer__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in writer_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WriterServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateAlbum = channel.unary_unary(
                '/writer.WriterService/CreateAlbum',
                request_serializer=writer__pb2.CreateAlbum_Request.SerializeToString,
                response_deserializer=writer__pb2.CreateAlbum_Response.FromString,
                _registered_method=True)
        self.RemoveAlbum = channel.unary_unary(
                '/writer.WriterService/RemoveAlbum',
                request_serializer=writer__pb2.RemoveAlbum_Request.SerializeToString,
                response_deserializer=writer__pb2.RemoveAlbum_Response.FromString,
                _registered_method=True)
        self.RemoveAlbumsByOwnerID = channel.unary_unary(
                '/writer.WriterService/RemoveAlbumsByOwnerID',
                request_serializer=writer__pb2.RemoveAlbumsByOwnerID_Request.SerializeToString,
                response_deserializer=writer__pb2.RemoveAlbumsByOwnerID_Response.FromString,
                _registered_method=True)
        self.CreateTrack = channel.unary_unary(
                '/writer.WriterService/CreateTrack',
                request_serializer=writer__pb2.CreateTrack_Request.SerializeToString,
                response_deserializer=writer__pb2.CreateTrack_Response.FromString,
                _registered_method=True)
        self.RemoveTrack = channel.unary_unary(
                '/writer.WriterService/RemoveTrack',
                request_serializer=writer__pb2.RemoveTrack_Request.SerializeToString,
                response_deserializer=writer__pb2.RemoveTrack_Response.FromString,
                _registered_method=True)


class WriterServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateAlbum(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveAlbum(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveAlbumsByOwnerID(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateTrack(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveTrack(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WriterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateAlbum': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAlbum,
                    request_deserializer=writer__pb2.CreateAlbum_Request.FromString,
                    response_serializer=writer__pb2.CreateAlbum_Response.SerializeToString,
            ),
            'RemoveAlbum': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveAlbum,
                    request_deserializer=writer__pb2.RemoveAlbum_Request.FromString,
                    response_serializer=writer__pb2.RemoveAlbum_Response.SerializeToString,
            ),
            'RemoveAlbumsByOwnerID': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveAlbumsByOwnerID,
                    request_deserializer=writer__pb2.RemoveAlbumsByOwnerID_Request.FromString,
                    response_serializer=writer__pb2.RemoveAlbumsByOwnerID_Response.SerializeToString,
            ),
            'CreateTrack': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTrack,
                    request_deserializer=writer__pb2.CreateTrack_Request.FromString,
                    response_serializer=writer__pb2.CreateTrack_Response.SerializeToString,
            ),
            'RemoveTrack': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveTrack,
                    request_deserializer=writer__pb2.RemoveTrack_Request.FromString,
                    response_serializer=writer__pb2.RemoveTrack_Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'writer.WriterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('writer.WriterService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WriterService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateAlbum(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/writer.WriterService/CreateAlbum',
            writer__pb2.CreateAlbum_Request.SerializeToString,
            writer__pb2.CreateAlbum_Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveAlbum(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/writer.WriterService/RemoveAlbum',
            writer__pb2.RemoveAlbum_Request.SerializeToString,
            writer__pb2.RemoveAlbum_Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveAlbumsByOwnerID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/writer.WriterService/RemoveAlbumsByOwnerID',
            writer__pb2.RemoveAlbumsByOwnerID_Request.SerializeToString,
            writer__pb2.RemoveAlbumsByOwnerID_Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateTrack(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/writer.WriterService/CreateTrack',
            writer__pb2.CreateTrack_Request.SerializeToString,
            writer__pb2.CreateTrack_Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveTrack(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/writer.WriterService/RemoveTrack',
            writer__pb2.RemoveTrack_Request.SerializeToString,
            writer__pb2.RemoveTrack_Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
